name: CI - Deploy To Host

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
    build:
      name: Initialize
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Install Dependency
          run: yarn

        - name: Build
          run: yarn build
          
        - name: Checks Deployment
          if: ${{ github.event_name == 'push' }}
          uses: JamesIves/github-pages-deploy-action@v4.2.3
          with:
            branch: host # The branch the action should deploy to.
            folder: build # The folder the action should deploy.
            target-folder: dev # The deploy the files to dev folder

        - name: Done
          run: echo 'Hooray!';