name: CI - Deploy to dev-server

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
    build:
      name: Build

      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@master

        - uses: borales/actions-yarn@v2.0.0
          with:
            cmd: install

        - uses: borales/actions-yarn@v2.0.0
          with:
            cmd: build
            
        - name: deploy
          run: yarn run deploy
