name: CI - Deploy to dev-server

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
    build:
      name: Build

      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: User Login  
          run: |
            git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
            git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
            
        - name: Install Dependency
          run: yarn

        - name: Build
          run: yarn build
            
        - name: Deploy
          run: yarn run deploy
