name: CI - Deploy to dev-server

on:
  push:
    branches: [ test-dev ]
  pull_request:
    branches: [ test-dev ]

jobs:
    build:
      name: Build

      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Install Dependency
          run: yarn

        - name: Build
          run: yarn build
          
        - name: Deploy
          if: ${{ github.event_name == 'push' }}
          uses: JamesIves/github-pages-deploy-action@v4.2.3
          with:
            branch: dev-server # The branch the action should deploy to.
            folder: build # The folder the action should deploy.
