name: Yarn Build and Deploy
on: push
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout 🛎️
          uses: actions/checkout@v2

        - name: Install 🔧
          run: yarn install

        - name: Install GH-Pages
          run: yarn add --D gh-pages
          
        - name: Build 🏗️
          run: yarn build

        - name: Deploy 🚨
          run: yarn run deploy
